# ── SSH KEY PAIR ──────────────────────────────────────────────────────────────
# A 4096 bit RSA pair is generated by Terraform. The private key is copied into
# Key Vault so operators retrieve it from there.
#
# IMPORTANT: tls_private_key stores the private key in Terraform STATE in
# plaintext. That is inherent to generating keys in Terraform, and is one reason
# state must be encrypted at rest, private, versioned, and readable only by the
# pipeline identity. Teams that cannot accept this generate keys outside
# Terraform and pass only the public key in.
resource "tls_private_key" "ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "azurerm_key_vault_secret" "ssh_private_key" {
  name         = "${var.vm_name}-ssh-private-key"
  value        = tls_private_key.ssh.private_key_pem
  key_vault_id = var.key_vault_id
  content_type = "application/x-pem-file"
  tags         = var.tags
}

resource "azurerm_key_vault_secret" "ssh_public_key" {
  name         = "${var.vm_name}-ssh-public-key"
  value        = tls_private_key.ssh.public_key_openssh
  key_vault_id = var.key_vault_id
  content_type = "text/plain"
  tags         = var.tags
}

# ── NETWORK SECURITY GROUP ────────────────────────────────────────────────────
# NIC level NSG. SSH from a private CIDR only, everything else inbound denied.
resource "azurerm_network_security_group" "vm" {
  name                = "nsg-${var.vm_name}"
  location            = var.location
  resource_group_name = var.resource_group_name

  security_rule {
    name                       = "Allow-SSH-From-Private"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "22"
    source_address_prefix      = var.nsg_allowed_ssh_source
    destination_address_prefix = "*"
  }

  security_rule {
    name                       = "Deny-All-Inbound"
    priority                   = 4096
    direction                  = "Inbound"
    access                     = "Deny"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }

  tags = var.tags
}

# ── NETWORK INTERFACE ─────────────────────────────────────────────────────────
# Private IP only. No public IP: reachable through Bastion or VPN.
resource "azurerm_network_interface" "vm" {
  name                = "nic-${var.vm_name}"
  location            = var.location
  resource_group_name = var.resource_group_name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = var.subnet_id
    private_ip_address_allocation = "Dynamic"
  }

  tags = var.tags
}

resource "azurerm_network_interface_security_group_association" "vm" {
  network_interface_id      = azurerm_network_interface.vm.id
  network_security_group_id = azurerm_network_security_group.vm.id
}

# ── VIRTUAL MACHINE ───────────────────────────────────────────────────────────
resource "azurerm_linux_virtual_machine" "vm" {
  name                = var.vm_name
  resource_group_name = var.resource_group_name
  location            = var.location
  size                = var.vm_size
  admin_username      = var.admin_username

  disable_password_authentication = true
  encryption_at_host_enabled      = var.encryption_at_host_enabled

  admin_ssh_key {
    username   = var.admin_username
    public_key = tls_private_key.ssh.public_key_openssh
  }

  network_interface_ids = [azurerm_network_interface.vm.id]

  os_disk {
    name                 = "osdisk-${var.vm_name}"
    caching              = "ReadWrite"
    storage_account_type = var.os_disk_type
    disk_size_gb         = var.os_disk_size_gb
  }

  source_image_reference {
    publisher = var.source_image.publisher
    offer     = var.source_image.offer
    sku       = var.source_image.sku
    version   = var.source_image.version
  }

  # System assigned identity, so workloads on the VM authenticate to Azure
  # without stored credentials.
  identity {
    type = "SystemAssigned"
  }

  # Managed boot diagnostics storage (no storage account URI needed).
  boot_diagnostics {}

  tags = var.tags

  # The NSG must be attached before the VM starts accepting traffic.
  depends_on = [azurerm_network_interface_security_group_association.vm]
}

# ── OPTIONAL: VM IDENTITY READS KEY VAULT SECRETS ─────────────────────────────
# The vault is in RBAC mode, so an access policy would be ignored. A role
# assignment is the correct mechanism. Off by default because creating role
# assignments requires User Access Administrator on the deploying identity.
resource "azurerm_role_assignment" "vm_key_vault_read" {
  count = var.grant_vm_key_vault_read ? 1 : 0

  scope                = var.key_vault_id
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azurerm_linux_virtual_machine.vm.identity[0].principal_id
}
